# Generated by Django 6.1.1 on 2026-10-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_DB',
            fields=[
                ('REf_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('DoB', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Mobile', models.IntegerField()),
                ('percentage', models.FloatField()),
            ],
        ),
    ]
