# Generated by Django 6.1.1 on 2026-10-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_info',
            fields=[
                ('vehicle_no_plate', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(max_length=15)),
                ('date_of_purchase', models.DateField()),
                ('colour', models.CharField(max_length=10)),
                ('owner_mob_no', models.IntegerField()),
                ('owner_address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='student_DB',
        ),
    ]
